### ISSUE TITLE
Patch DOM: moving a component that returns a Fragment only moves the first element in the fragment

### ISSUE THREAD

**Issue by Raven-79** [angelsolaorbaiceta/fe-fwk-book#267]
**Describe the bug**
When a component is returning a fragment and the `arraysDiffSequence` generates a `move` operation for the component
only the first element of the component is moved instead of the whole component

**To Reproduce**
Try to render the following code and click the reverse button
```js
const Child = defineComponent({
  render() {
    return hFragment([
      h('h2', {}, ['The User is ', this.props.user.name]),
      h('h4', {}, ['the id is ', this.props.user.id]),
    ])
  },
})

const Container = defineComponent({
  state() {
    return {
      users: [
        { id: 1, name: 'Test1' },
        { id: 2, name: 'Test2' },
      ],
    }
  },
  render() {
    return h('div', {}, [
      h(
        'button',
        {
          on: {
            click: () => {
              this.updateState({
                users: [...this.state.users].reverse(),
              })
            },
          },
        },
        ['Reverse']
      ),
      ...this.state.users.map((user) => h(Child, { user, key: user.id })),
    ])
  },
})

createApp(Container).mount(document.body)
```

**Expected behavior**
The Components get correctly reversed

**Screenshots**
initial render:
![image](https://github.com/angelsolaorbaiceta/fe-fwk-book/assets/51274969/a55e5a97-ffe9-4096-b8cb-fe89faf25d14)
after reverse:
![image](https://github.com/angelsolaorbaiceta/fe-fwk-book/assets/51274969/c615e3df-1024-4ff9-aead-018bec607478)

**Additional context**

**Comment by angelsolaorbaiceta** [comment]
Hi there @Raven-79 👋👋

Thanks for taking the time to report this issue. I will take a look at soon as I find some time.

**Comment by angelsolaorbaiceta** [comment]
I reproduced the issue with a test and understood the root cause, which is a bit tricky.
Inside the `patchChildren()` function, the `ARRAY_DIFF_OP.MOVE` operation should move not only the first element, but all of them in case they are part of a fragment.

```js
 case ARRAY_DIFF_OP.MOVE: {
        const oldChild = oldChildren[originalIndex]
        const newChild = newChildren[index]
        const el = oldChild.el 👈
        const elAtTargetIndex = parentEl.childNodes[index + offset]

        parentEl.insertBefore(el, elAtTargetIndex)
        patchDOM(oldChild, newChild, parentEl, hostComponent)

        break
}
```

I need a bit of time to think about what the best solution would be here. Ideally it should be simple and shouldn't change things a lot, so to not confuse future readers when they compare the code they wrote following the book and the code that's in the repo.

Again, super thanks @Raven-79 for reporting this very interesting bug. I will be fixing it soon and explaining the solution with lots of detail.

**Comment by Raven-79** [comment]
hello @angelsolaorbaiceta 
Thanks a lot for the fix, and thanks for the book! I really enjoyed reading it; it was both fun and rich with information.
